export type MasteryBand = "unseen" | "introduced" | "developing" | "stable" | "mastered";
export type EvidenceSnapshot = { attempts:number; misconceptions:number; hintUse:number; retries:number; sourceReturns:number; confidence:number };
export type ActivityLearningState = EvidenceSnapshot & { activityId:string; score:number; band:MasteryBand; needsRemediation:boolean };
export type ConceptInput = { id:string; label:string; chapterId:string };
export type ActivityInput = { id:string; chapterId:string; conceptIds:string[] };
export type LearningProgressInput = { viewed:string[]; completed:string[]; attempts:Record<string,number>; mastered:string[]; current:string; evidence?:{ misconception?:Record<string,number>; hintUse?:Record<string,number>; retries?:Record<string,number>; sourceReturns?:Record<string,number>; confidence?:Record<string,number> } };
export type ConceptLearningState = { conceptId:string; label:string; chapterId:string; score:number; band:MasteryBand; supportingActivities:string[]; remediationActivities:string[] };
export type NextLearningAction = { kind:"introduce"|"retrieve"|"remediate"|"transfer"|"advance"; activityId?:string; chapterId:string; reason:string; priority:number };
function clamp(value:number,min=0,max=1){return Math.min(max,Math.max(min,value));}
export function evidenceForActivity(activityId:string,progress:LearningProgressInput):EvidenceSnapshot{const e=progress.evidence??{};return{attempts:Math.max(0,progress.attempts?.[activityId]??0),misconceptions:Math.max(0,e.misconception?.[activityId]??0),hintUse:Math.max(0,e.hintUse?.[activityId]??0),retries:Math.max(0,e.retries?.[activityId]??0),sourceReturns:Math.max(0,e.sourceReturns?.[activityId]??0),confidence:clamp(e.confidence?.[activityId]??0)};}
export function activityLearningState(activityId:string,progress:LearningProgressInput):ActivityLearningState{const e=evidenceForActivity(activityId,progress);if(e.attempts===0)return{activityId,...e,score:0,band:"unseen",needsRemediation:false};const successRate=clamp((e.attempts-Math.min(e.attempts,e.misconceptions))/e.attempts);const repetition=clamp(e.attempts/3);const hintDependence=clamp(e.hintUse/Math.max(1,e.attempts));const remediationSignal=clamp((e.misconceptions+e.sourceReturns+e.retries)/4);const score=clamp(.5*successRate+.2*repetition+.2*e.confidence+.1*(1-hintDependence)-.2*remediationSignal);const needsRemediation=e.misconceptions>0||e.sourceReturns>0||score<.55;const band:MasteryBand=score>=.85&&e.attempts>=3&&!needsRemediation?"mastered":score>=.7?"stable":score>=.45?"developing":"introduced";return{activityId,...e,score,band,needsRemediation};}
export function buildConceptLearningStates(concepts:ConceptInput[],activities:ActivityInput[],progress:LearningProgressInput):ConceptLearningState[]{return concepts.map(c=>{const ids=activities.filter(a=>a.conceptIds.includes(c.id)).map(a=>a.id);const states=ids.map(id=>activityLearningState(id,progress));const attempted=states.filter(s=>s.attempts>0);const score=attempted.length?attempted.reduce((sum,s)=>sum+s.score,0)/attempted.length:0;const band:MasteryBand=attempted.length===0?"unseen":score>=.85&&attempted.length>=Math.min(2,ids.length)?"mastered":score>=.7?"stable":score>=.45?"developing":"introduced";return{conceptId:c.id,label:c.label,chapterId:c.chapterId,score,band,supportingActivities:ids,remediationActivities:states.filter(s=>s.needsRemediation).map(s=>s.activityId)};});}
export function recommendNextLearningAction(concepts:ConceptInput[],activities:ActivityInput[],progress:LearningProgressInput):NextLearningAction{const states=buildConceptLearningStates(concepts,activities,progress);const current=progress.current||"ch-01";const remediation=states.flatMap(c=>c.remediationActivities.map(activityId=>({c,activityId}))).map(({c,activityId})=>{const s=activityLearningState(activityId,progress);return{kind:"remediate" as const,activityId,chapterId:c.chapterId,reason:`${c.label} shows unresolved learning evidence; revisit the activity before advancing.`,priority:1-s.score};}).sort((a,b)=>b.priority-a.priority)[0];if(remediation)return remediation;const retrieval=states.filter(c=>c.chapterId===current&&c.band!=="mastered").flatMap(c=>c.supportingActivities.map(activityId=>({c,activityId}))).map(({c,activityId})=>({kind:"retrieve" as const,activityId,chapterId:c.chapterId,reason:`Retrieve ${c.label} before introducing another idea.`,priority:1-c.score})).sort((a,b)=>b.priority-a.priority)[0];if(retrieval)return retrieval;const next=activities.find(a=>a.chapterId!==current&&!progress.viewed.includes(a.chapterId))?.chapterId;if(next)return{kind:"advance",chapterId:next,reason:"Current chapter evidence is stable enough to introduce the next chapter.",priority:.5};const fallback=states.find(c=>c.band!=="mastered");if(fallback)return{kind:"introduce",activityId:fallback.supportingActivities[0],chapterId:fallback.chapterId,reason:`Introduce ${fallback.label}; there is not yet enough learner evidence.`,priority:.25};return{kind:"transfer",chapterId:current,reason:"Core activities are stable; the next step should test transfer in a novel context.",priority:.1};}
